@startuml prototipov1

class Blockchain{
    - chain: [{Block}]
    + createGenesisBlock()
    + getChain()
    + addBlock(block)
    + getLastBlock()
}

class Miner {
    - blockchain : Blockchain
    - mempool : Mempool
    + hashBlock(): String
    + proofOfWork(): Int
    + mineBlock()
}

class Mempool{
    - pendingTransactions: [{Transaction}]
    + addTransaction()
    + getPendingTransactions()
    + clearPendingTransactions()

}

class Block{
    - index: Int 
    - timeStamp: Int 
    - nonce: Int
    - hash: String 
    - previousBlockHash: String
    - Transactions:[{Transaction}]
    + createBlock()
    + addTransaction(transaction)
    + getTransactions()
}

class Transaction{
    - transactionID: String 
    - coinAmount: Int 
    - senderPublickey: String
    - receiverPublicKey: String
    - isConfirmed: boolean
}

class Wallet{
    - blockchain : Blockchain
    - name: String
    - publicKey: String
    - balance: Int
    - Transactions:[{Transaction}]
    + sendCoin()
    + updateTransactions()
    + updateBalance()
    + generateRandomPublicKey()
    + getWallet()

}

class Coin{
    - name: String
    - ticker: String 
    - initialSupply: Int
    - maxSupply: Int
    + getCoin()
    + mintCoinbase()
}

Miner ..> Block : uses
Miner --> Blockchain : associate
Miner --> Mempool : associate
Wallet --> Blockchain : associate
Blockchain ..> Block : uses
Blockchain ..> Coin : uses
Block ..> Transaction : uses

@enduml