@startuml prototipov1

class Blockchain{
    - chain: [{Block}]
}

class Miner{
    +proofOfWork()
}

class Wallet{
    +sendCoin()
}

class Block{
    - index: Int 
    - timeStamp: Int 
    - nonce: Int
    - hash: String 
    - previousBlockHash: String
    - Transactions:[{Transaction}]
    + createBlock()
}

class Transaction{

}

class Coin{

}

class Mempool{

}

@enduml