@startuml prototipov1

class Blockchain{
    - chain: [{Block}]
    + getChain()
    + addBlock(block)
}

class Miner{
    + hashBlock()
    + proofOfWork()
}

class Wallet{
    + sendCoin()
}

class Block{
    - index: Int 
    - timeStamp: Int 
    - nonce: Int
    - hash: String 
    - previousBlockHash: String
    - Transactions:[{Transaction}]
    + createBlock()
    + addTransaction(transaction)
    + getTransactions()
}

class Transaction{
    - transactionID: String 
    - coinAmount: Int 
    - senderPublickey: String
    - receiverPublicKey: String
    - isConfirmed: boolean
}

class Coin{

}

class Mempool{
    - pendingTransactions: [{Transaction}]
    + addTransaction(transaction)
}

@enduml